In [8]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])


print("shape", a.shape)



shape (3, 3)


Three Dimensional arrary

In [74]:
import numpy as np 
b = np.array([[[1,2,3], [4,5,6], [7,8,9] ] , [[1,2,3] ,[4,5,6],[7,8,9]]] )
print("shape", b.shape)
print(b)



shape (2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [27]:
import numpy as np

c = np.zeros((2,3,4))



print("shape", c.shape)

d = np.random.randint(1,100,(2,3,4))


print(d)
print("shape", d.shape)

shape (2, 3, 4)
[[[36 49 59 77]
  [ 5  5 64 77]
  [60 83 60 74]]

 [[ 7  7 75 62]
  [34 49 36 51]
  [90  6 70 22]]]
shape (2, 3, 4)


single dimensional 

In [ ]:
import numpy as np 

e  = np.array([
    [
        np.array([1,2,3]), np.array([4,5,6])  
    ],
    [
        np.array([7,8]) , np.array([10,11,12])
    ]
    ] , dtype=object )

print("shape", e.shape) 

# single dimensional 


    


shape (2, 2)


In [ ]:
import  numpy as np

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] ]

lenght = max(len(row) for block in data  for row in block)

for i in data:
    for j in i:
        l = len(j)

print(l)

5


Tasks

1. syncthtic data
2. 


In [ ]:
# indexing
import  numpy as np

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] ]

print(data)

print(data[0])

print(data[-1])

# task
# on the 0 th  index  take the 1st element 




[[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]]
[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [44]:
# slicing

import numpy as np 

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] , [[1,2,3,4,5,], [1,2,3,4,5]],[[1,2,3,4,5,], [1,2,3,4,5]]]

print(data[0:2])

[[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]]


In [ ]:
# filering
import numpy as np

data =np.array([1,2,3,4,55,6,])

# bool indexing
print(data > 3)

# bool filter by contidion
print(data[data > 3])


[False False False  True  True  True]
[ 4 55  6]


In [ ]:

import numpy  as np

marks = np.array([40,20,34,60,78,90])

print(marks > 40)
print(marks[marks < 40])





[False False False  True  True  True]
[20 34]


In [64]:
# reshaping

import numpy as np



data = np.arange(1,13)

# c = np.zeros((2,3,4))


reshaped  =  data.reshape(2,6)

print(reshaped)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# split
import numpy as np

data = np.arange(1,31)
# does not take the last element 
reshaped = data.reshape(3,10)

print(reshaped)
print("horizontal", np.hsplit(reshaped, 2))
print("verical" ,np.vsplit(reshaped, 3))


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])]
verical [array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]


In [48]:
import numpy as  np

sales_q1 = np.array([[2300, 1500, 4200],
                     [3100, 2000, 1900],
                     [2500, 2700, 2900]])

sales_q2 = np.array([[2800, 1600, 4000],
                     [3200, 2500, 2100],
                     [2600, 3000, 3100]])



total_sales = sales_q1 + sales_q2

print("Total Sales:\n", total_sales)

r_total_sales = np.sum(total_sales, axis=1)

print("Total Sales per Region:\n", r_total_sales)

region_average = np.mean(total_sales, axis=1)


print("Average Sales per Region:\n", region_average)
print("Average Round",np.round(region_average[:1]))

highest_region = np.argmax(region_average)

print("Region with Highest Sales:", highest_region)

difference = sales_q2 - sales_q1

print("Difference between Q2 and Q1:\n", difference)

Total Sales:
 [[5100 3100 8200]
 [6300 4500 4000]
 [5100 5700 6000]]
Total Sales per Region:
 [16400 14800 16800]
Average Sales per Region:
 [5466.66666667 4933.33333333 5600.        ]
Average Round [5467.]
Region with Highest Sales: 2
Difference between Q2 and Q1:
 [[ 500  100 -200]
 [ 100  500  200]
 [ 100  300  200]]


In [ ]:
# task 2
import numpy as np

scores = np.array([
      [65, 78, 90],
    [45, 55, 60],
    [88, 92, 79],
    [35, 40, 30]

])

# print(marks[marks < 40])

passed = scores[scores > 70] 

print("Passed Scores:", passed)

# :2 = first two rows
# :  = all columns

first_2_students = scores[:2, :]  
print("First 2 Students' Scores:\n", first_2_students)

second_student_scores = scores[1, :]
print("Second Student's Scores:", second_student_scores)


# ::-1 flip rows
flipped_scores = scores[::-1, ::-1]
print("Flipped Scores:\n", flipped_scores)






Passed Scores: [78 90 88 92 79]
First 2 Students' Scores:
 [[65 78 90]
 [45 55 60]]
Second Student's Scores: [45 55 60]
Flipped Scores:
 [[30 40 35]
 [79 92 88]
 [60 55 45]
 [90 78 65]]


In [ ]:
# task 3
import numpy  as np 

sales_2024 = np.array([[100, 200], [300, 400]])
sales_2025 = np.array([[150, 250], [350, 450]])

combine = np.array(sales_2024 + sales_2025 )
print("Combined Sales:\n", combine)

# putting one array on side by side.
# need same no of colums
coimbed_sales = np.vstack((sales_2024, sales_2025))
print("Combined Sales (Vertical Stack):\n", coimbed_sales)


# .flatten convert multi dimensional to single dimensional
flattern_sales = coimbed_sales.flatten()
print("Flattened Sales:\n", flattern_sales)








Combined Sales:
 [[250 450]
 [650 850]]
Combined Sales (Vertical Stack):
 [[100 200]
 [300 400]
 [150 250]
 [350 450]]
Flattened Sales:
 [100 200 300 400 150 250 350 450]


In [ ]:
# Arithmetic operations

import numpy  as np


# arr = np.array([1, 2, 3, 4, 5])

a = np.array([1,2,3])
b = np.array([4,5,6])

print("add", a+b)
print("sub",a-b)
print("multipication", a*b)
print("division", a/b)
print("modulus", a%b)
print("exponent", a**b)
print("floor div", a//b)






add [5 7 9]
sub [-3 -3 -3]
multipication [ 4 10 18]
division [0.25 0.4  0.5 ]
modulus [1 2 3]
exponent [  1  32 729]
floor div [0 0 0]


In [6]:
# Scaler operations
# automatically applies to all the elements of the array

import numpy as np

a = np.array([1,2,3])

print(a + 5)
print(a - 5)
print(a * 5)
print(a / 5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [61]:
# dot
# matrix multiplication

import numpy as np


A = np.array([[1, 2,3],
              [3, 4,4]
              ])
B = np.array([[5, 6,6],
              [7, 8,5]])

# A = np.array([[1, 2],
#               [3, 4]])
# B = np.array([[5, 6],
#               [7, 8]])

#       R   c

# 3:2
# first table  column = second table rows
c = np.transpose(B)


# A*B
c = np.dot(A,c)
print("shape", A.shape)
print("shape",B.shape)
print("C = " , c)
# print(np.dot(A, B))

shape (2, 3)
shape (2, 3)
C =  [[35 38]
 [63 73]]


In [22]:
# logical operations
import numpy as np

a = np.array([10, 20, 30])
b = np.array([20, 20, 10])

print(a == b)   
print(a > b)   
print(a <= 20) 


# Logical operations
print(np.logical_and(a > 10, b < 30))  


[False  True False]
[False False  True]
[ True  True False]
[False  True  True]


In [ ]:
# Broadcasting
import numpy as np

data = np.array([1,2,3,4])

print(data +2)




[3 4 5 6]


In [2]:
# Aggrigation functions  = sumarrizing 

import numpy as np 

data = np.array([1,2,3,4,])

# print(data + 1)
print("sum" ,np.sum(data))
print("max", np.max(data))
print("avg", np.average(data))
print("mean" , np.mean(data))
print("median", np.median(data))
print("sd", np.std(data))


data2 = np.array([[1,2,3], [1,2,3],[1,2,3]])

print("sum", np.sum(data2))
# 1 = row
print("sum axis = 1 : ",np.sum(data2, axis=1) )
# 0 = colum
print("sum axis = 0 : ", np.sum(data2, axis =0))

data3 = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,25,3]],])

print(data3)
print("sum" , np.sum(data3))
print("sum axis = 0 colums" ,np.sum(data3, axis = 0))
print("sum axis = 1  row" ,np.sum(data3, axis = 1))
print("sum axis = 2  row" ,np.sum(data3, axis = 2))
print("mean", np.mean(data3))
print("argmin", np.argmin(data3))
print("argmax", np.argmax(data3))













sum 10
max 4
avg 2.5
mean 2.5
median 2.5
sd 1.118033988749895
sum 18
sum axis = 1 :  [6 6 6]
sum axis = 0 :  [3 6 9]
[[[ 1  2  3]
  [ 1  2  3]]

 [[ 1  2  3]
  [ 1 25  3]]]
sum 47
sum axis = 0 colums [[ 2  4  6]
 [ 2 27  6]]
sum axis = 1  row [[ 2  4  6]
 [ 2 27  6]]
sum axis = 2  row [[ 6  6]
 [ 6 29]]
mean 3.9166666666666665
argmin 0
argmax 10


In [ ]:
# fancy indexing
import numpy as np

a = np.array([12,4,5,6,334,77,22])
a1 = np.array([[33,6,3,122,44],[12,45,2,36,754]])
# normal 
b = a[:4]
b1 =a1[:3]
# fancy
c = a[[6,5,0]]

#        r      c
c1 = a1[[0,1],[1,4]]

# ONE DIMENTIONAL
print("Normal",b)
print("fancy",c)

# Two Dimentional
print("Normal",b1)
print("fancy",c1)


# print(a[:])



Normal [12  4  5  6]
fancy [22 77 12]
Normal [[ 33   6   3 122  44]
 [ 12  45   2  36 754]]
fancy [  6 754]


In [50]:
# select multiple rows in specific  colums

import numpy as np 

markes = np.array([[[23,45,34,45,54],[345,23,64,23,65],[323,54,43,23,45]],[[33,54,54,5,4],[45,5,4,42,2],[21,45,223,1,10]]])

# []

# [[],[]]

# [[[]]]
print(markes)
print(markes[0,1,4])
# print(markes[[1,2,3][]])



[[[ 23  45  34  45  54]
  [345  23  64  23  65]
  [323  54  43  23  45]]

 [[ 33  54  54   5   4]
  [ 45   5   4  42   2]
  [ 21  45 223   1  10]]]
65


In [77]:
# two dimensionl  -  normal & fancy indexing = 5 times 
# three dimensionl -  normal & fancy indexing = 5 times

import numpy as np

a = np.random.randint(1,100,size=(3,4,7))

print(a)

[[[79 65 78 27 46 67 10]
  [82 52 42 41 28 34 51]
  [91 55 69  9 30 22 64]
  [56 20 36  8 92  6 91]]

 [[80 86  6 92 48 33 97]
  [87 20 10 65 80 63 85]
  [16 11 83 90 76 32 17]
  [82 31 98 12 42 74 16]]

 [[70 16 45 96 61 61 24]
  [51 18  7 57 57 21 73]
  [41 98 79 85 38  3 31]
  [38 29 91 87 83  1 81]]]


In [ ]:
#1 2d
import numpy as np

a = np.array(
    [
    [95, 29, 35],
    [65, 10 ,73],
    [34, 70, 24],
    ]
    )

b=a[:2]
print(b)

c = a[[1],[2]]
print(c)

[[95 29 35]
 [65 10 73]]
[73]


In [59]:
#2 2d
import numpy as np 
a = np.array([[34,55,65],[23,54,664],[123,65,23]])

b= a[:2]
print(b)

c = a[1 ,2]
print(c)

[[ 34  55  65]
 [ 23  54 664]]
664


In [60]:
#3 3d
import numpy as np
a = np.array([[4,3,2],[231,2123,45],[433,23,76]])

b=a[:1]
print(b)

c = a[2,0]
print(c)

[[4 3 2]]
433


In [62]:
#4 2d
import numpy as np

a = np.array([[43,22,56,1],[65,32,8,65], [65,23,65,45]])

b = a[:2]
print(b)

c = a[1,3]
print(c)

[[43 22 56  1]
 [65 32  8 65]]
65


In [64]:
#5 2d 
import numpy as np

a = np.array([[334,23,23],[23123,3545,454],[212,4,3]])

b= a[1:]
print(b)

c= a[2,2]
print(c)

[[23123  3545   454]
 [  212     4     3]]
3


In [68]:
#1 3d
import numpy as np

a = np.array([[[12,4,5],[332,34,5]],[[34,2,5,],[65,75,32]]])

b= a[:1]
print(b)

c = a[0,1,0]

print(c)

[[[ 12   4   5]
  [332  34   5]]]
332


In [69]:
#2 3d
import numpy as np

a = np.array([[[2,3,2],[23,44,65],[32,5,6]],[[12,44,54],[234,54,65],[32,54,66]]])

b= a[:1]
print(b)

c = a[1,2,2]
print(c)

[[[ 2  3  2]
  [23 44 65]
  [32  5  6]]]
66


In [72]:
#3 3d
import numpy as np

a = np.array([[[68, 13, 60],
  [ 5, 45, 62,],
  [99 ,95, 17]],

 [[34,  4, 21],
  [65, 11 ,99],
  [15, 56, 16]],

 [[ 1, 34, 16],
  [56 ,88, 95],
  [11 ,66, 36]]])

b= a[:2]
print(b)

c = a[2,1,2]
print(c)

[[[68 13 60]
  [ 5 45 62]
  [99 95 17]]

 [[34  4 21]
  [65 11 99]
  [15 56 16]]]
95


In [74]:
#4 3d
import numpy as np

a = np.array([[[12 ,22, 93],
  [ 9, 49, 36],
  [63, 73, 38]],

 [[43, 96, 76],
  [58, 94, 57],
  [83, 73 ,98]],

 [[83, 39, 14],
  [35, 27, 21],
  [45 ,67, 79]]])

b= a[:1]
print(b)

c= a[2,1,0]
print(c)

[[[12 22 93]
  [ 9 49 36]
  [63 73 38]]]
35


In [76]:
#5 3d
import numpy as np

a = np.array([[[40, 30, 54],
  [42, 50, 83],
  [23 ,37, 96]],

 [[25, 53, 74],
  [18 ,54, 17],
  [68 ,31 ,45]],

 [[52 ,18,  2],
  [57, 77, 95],
  [59, 58,  9]]])

b= a[:-1]
print(b)

c = a[2,2,2]
print(c)

[[[40 30 54]
  [42 50 83]
  [23 37 96]]

 [[25 53 74]
  [18 54 17]
  [68 31 45]]]
9


Imagine you have sales data for 2 years, each year has 2 stores, and each store has 3 products:

sales = np.array([
    [[100, 200, 300],
     [150, 250, 350]],   # Year 1
    [[120, 220, 320],
     [180, 280, 380]]    # Year 2
])

Now:

Operation	Meaning	Example

np.sum(sales)	Total sales (all years, stores, products)	Business total
np.sum(sales, axis=0)	Total sales per store & product (all years combined)	Compare store performance
np.mean(sales, axis=2)	Avg sales per store (across products)	Product mix analysis






arr = np.array([10, 20, 30, 40, 50, 60])
result = arr[(arr > 20) & (arr < 50)]
print(result)





Difference between fancy indexing and normal indexing




Task: Weather Data Analysis (3D NumPy Array)

📖 Scenario:

You are a data analyst at a climate research center.
You’ve been given a 3D NumPy array representing daily temperature readings (in °C) collected from 3 cities over 4 weeks (7 days each).

Array Dimensions: (3, 4, 7)

Axis 0 → Cities (3)

Axis 1 → Weeks (4)

Axis 2 → Days (7)


So data[city, week, day] gives temperature for a specific city on a specific day of a specific week. Use random for genarating exampl 15 degree to 60 degree.

Your Tasks
Task 1: Calculate the average temperature per city for all weeks.
Output shape: (3,)
(Hint: use axis=(1,2) to average across weeks & days)

Task 2: Find the hottest day of the month (max temperature) for each city.

Output shape: (3,)
(Hint: use np.max() with appropriate axis)

Task 3: Extract all temperature values above 35°C across all cities.

Return them as a flat array.

(Hint: Boolean fancy indexing)

 Task 4: Replace all temperatures below 20°C with the city’s weekly average.

(Hint: Use broadcasting and fancy indexing)

Task 5: Compute which city had the highest overall average temperature across the 4 weeks.

Output: city index (0, 1, or 2)


Task 6: Get a 2D array of each city's average temperature per week.

Output shape: (3, 4)
(Hint: average across days → axis=2)

Task 7 (Bonus): Normalize all temperatures city-wise

so that each city’s data has values between 0 and 1.

(Hint: (x - x.min()) / (x.max() - x.min()), done per city)

In [111]:
# Weather Data Analysis

import numpy as np

weather_data = np.random.randint(15,61,size=(3,4,7))

print(weather_data)

average_temperature_city = np.mean(weather_data , axis=(1,2))

print("average temperature per city for all weeks : ", average_temperature_city.round(1))

print("shape :" , average_temperature_city.shape)


max_temperature_city = np.max(weather_data, axis=(1,2))
print("Hottest temperature per city : ", max_temperature_city)
print("shape:" , max_temperature_city.shape)


flatten_data = weather_data.flatten()
print("Flatten Weather Data :",flatten_data)

temperature_above_35 = weather_data[weather_data > 35]
print("Temperature above 35 : ",temperature_above_35)


weekly_avg = np.mean(weather_data , axis=2)
print("weeky Avg   : ", weekly_avg)


find_below_20 = weather_data < 20
# find_below_20 = [weather_data < 20]

print("find Below 20",find_below_20)

print("sum below 20 :", find_below_20.sum())

weekly_avg_reddata  =  weekly_avg[:,:,np.newaxis]

print("shape : weekly Avg : ", weekly_avg_reddata.shape)
print("shape : find below_ 20 : ", find_below_20.shape)

print("weekly_avg_redata : ", weekly_avg_reddata)

weather_data[find_below_20] = weekly_avg_reddata[find_below_20[:,:,0]]

# weather_data[find_below_20] = weekly_avg_reddata[find_below_20]

print("weather_data : 20 : ",weather_data[find_below_20])
# print("weekly_avg : 20 : ", weekly_avg_reddata[find_below_20])

# print("weather_data",weather_data)


    




[[[35 28 21 37 38 49 40]
  [46 22 44 20 32 39 47]
  [29 51 25 43 31 55 40]
  [39 42 43 39 58 32 40]]

 [[33 25 44 48 25 57 29]
  [24 26 59 49 40 29 38]
  [50 16 52 29 41 48 59]
  [57 19 44 18 23 24 21]]

 [[38 17 48 42 49 55 33]
  [55 48 16 32 60 16 55]
  [56 30 15 58 52 25 37]
  [53 25 26 40 33 24 43]]]
average temperature per city for all weeks :  [38.  36.7 38.6]
shape : (3,)
Hottest temperature per city :  [58 59 60]
shape: (3,)
Flatten Weather Data : [35 28 21 37 38 49 40 46 22 44 20 32 39 47 29 51 25 43 31 55 40 39 42 43
 39 58 32 40 33 25 44 48 25 57 29 24 26 59 49 40 29 38 50 16 52 29 41 48
 59 57 19 44 18 23 24 21 38 17 48 42 49 55 33 55 48 16 32 60 16 55 56 30
 15 58 52 25 37 53 25 26 40 33 24 43]
Temperature above 35 :  [37 38 49 40 46 44 39 47 51 43 55 40 39 42 43 39 58 40 44 48 57 59 49 40
 38 50 52 41 48 59 57 44 38 48 42 49 55 55 48 60 55 56 58 52 37 53 40 43]
weeky Avg   :  [[35.42857143 35.71428571 39.14285714 41.85714286]
 [37.28571429 37.85714286 42.14285714 29.42857

TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions