In [8]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])


print("shape", a.shape)



shape (3, 3)


Three Dimensional arrary

In [74]:
import numpy as np 
b = np.array([[[1,2,3], [4,5,6], [7,8,9] ] , [[1,2,3] ,[4,5,6],[7,8,9]]] )
print("shape", b.shape)
print(b)



shape (2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [27]:
import numpy as np

c = np.zeros((2,3,4))



print("shape", c.shape)

d = np.random.randint(1,100,(2,3,4))


print(d)
print("shape", d.shape)

shape (2, 3, 4)
[[[36 49 59 77]
  [ 5  5 64 77]
  [60 83 60 74]]

 [[ 7  7 75 62]
  [34 49 36 51]
  [90  6 70 22]]]
shape (2, 3, 4)


single dimensional 

In [ ]:
import numpy as np 

e  = np.array([
    [
        np.array([1,2,3]), np.array([4,5,6])  
    ],
    [
        np.array([7,8]) , np.array([10,11,12])
    ]
    ] , dtype=object )

print("shape", e.shape) 

# single dimensional 


    


shape (2, 2)


In [ ]:
import  numpy as np

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] ]

lenght = max(len(row) for block in data  for row in block)

for i in data:
    for j in i:
        l = len(j)

print(l)

5


Tasks

1. syncthtic data
2. 


In [ ]:
# indexing
import  numpy as np

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] ]

print(data)

print(data[0])

print(data[-1])

# task
# on the 0 th  index  take the 1st element 




[[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]]
[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [44]:
# slicing

import numpy as np 

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] , [[1,2,3,4,5,], [1,2,3,4,5]],[[1,2,3,4,5,], [1,2,3,4,5]]]

print(data[0:2])

[[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]]


In [ ]:
# filering
import numpy as np

data =np.array([1,2,3,4,55,6,])

# bool indexing
print(data > 3)

# bool filter by contidion
print(data[data > 3])


[False False False  True  True  True]
[ 4 55  6]


In [ ]:

import numpy  as np

marks = np.array([40,20,34,60,78,90])

print(marks > 40)
print(marks[marks < 40])





[False False False  True  True  True]
[20 34]


In [64]:
# reshaping

import numpy as np



data = np.arange(1,13)

# c = np.zeros((2,3,4))


reshaped  =  data.reshape(2,6)

print(reshaped)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# split
import numpy as np

data = np.arange(1,31)
# does not take the last element 
reshaped = data.reshape(3,10)

print(reshaped)
print("horizontal", np.hsplit(reshaped, 2))
print("verical" ,np.vsplit(reshaped, 3))


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])]
verical [array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]


In [48]:
import numpy as  np

sales_q1 = np.array([[2300, 1500, 4200],
                     [3100, 2000, 1900],
                     [2500, 2700, 2900]])

sales_q2 = np.array([[2800, 1600, 4000],
                     [3200, 2500, 2100],
                     [2600, 3000, 3100]])



total_sales = sales_q1 + sales_q2

print("Total Sales:\n", total_sales)

r_total_sales = np.sum(total_sales, axis=1)

print("Total Sales per Region:\n", r_total_sales)

region_average = np.mean(total_sales, axis=1)


print("Average Sales per Region:\n", region_average)
print("Average Round",np.round(region_average[:1]))

highest_region = np.argmax(region_average)

print("Region with Highest Sales:", highest_region)

difference = sales_q2 - sales_q1

print("Difference between Q2 and Q1:\n", difference)

Total Sales:
 [[5100 3100 8200]
 [6300 4500 4000]
 [5100 5700 6000]]
Total Sales per Region:
 [16400 14800 16800]
Average Sales per Region:
 [5466.66666667 4933.33333333 5600.        ]
Average Round [5467.]
Region with Highest Sales: 2
Difference between Q2 and Q1:
 [[ 500  100 -200]
 [ 100  500  200]
 [ 100  300  200]]


In [ ]:
# task 2
import numpy as np

scores = np.array([
      [65, 78, 90],
    [45, 55, 60],
    [88, 92, 79],
    [35, 40, 30]

])

# print(marks[marks < 40])

passed = scores[scores > 70] 

print("Passed Scores:", passed)

# :2 = first two rows
# :  = all columns

first_2_students = scores[:2, :]  
print("First 2 Students' Scores:\n", first_2_students)

second_student_scores = scores[1, :]
print("Second Student's Scores:", second_student_scores)


# ::-1 flip rows
flipped_scores = scores[::-1, ::-1]
print("Flipped Scores:\n", flipped_scores)






Passed Scores: [78 90 88 92 79]
First 2 Students' Scores:
 [[65 78 90]
 [45 55 60]]
Second Student's Scores: [45 55 60]
Flipped Scores:
 [[30 40 35]
 [79 92 88]
 [60 55 45]
 [90 78 65]]


In [ ]:
# task 3
import numpy  as np 

sales_2024 = np.array([[100, 200], [300, 400]])
sales_2025 = np.array([[150, 250], [350, 450]])

combine = np.array(sales_2024 + sales_2025 )
print("Combined Sales:\n", combine)

# putting one array on side by side.
# need same no of colums
coimbed_sales = np.vstack((sales_2024, sales_2025))
print("Combined Sales (Vertical Stack):\n", coimbed_sales)


# .flatten convert multi dimensional to single dimensional
flattern_sales = coimbed_sales.flatten()
print("Flattened Sales:\n", flattern_sales)








Combined Sales:
 [[250 450]
 [650 850]]
Combined Sales (Vertical Stack):
 [[100 200]
 [300 400]
 [150 250]
 [350 450]]
Flattened Sales:
 [100 200 300 400 150 250 350 450]


In [ ]:
# Arithmetic operations

import numpy  as np


# arr = np.array([1, 2, 3, 4, 5])

a = np.array([1,2,3])
b = np.array([4,5,6])

print("add", a+b)
print("sub",a-b)
print("multipication", a*b)
print("division", a/b)
print("modulus", a%b)
print("exponent", a**b)
print("floor div", a//b)






add [5 7 9]
sub [-3 -3 -3]
multipication [ 4 10 18]
division [0.25 0.4  0.5 ]
modulus [1 2 3]
exponent [  1  32 729]
floor div [0 0 0]


In [6]:
# Scaler operations
# automatically applies to all the elements of the array

import numpy as np

a = np.array([1,2,3])

print(a + 5)
print(a - 5)
print(a * 5)
print(a / 5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [61]:
# dot
# matrix multiplication

import numpy as np


A = np.array([[1, 2,3],
              [3, 4,4]
              ])
B = np.array([[5, 6,6],
              [7, 8,5]])

# A = np.array([[1, 2],
#               [3, 4]])
# B = np.array([[5, 6],
#               [7, 8]])

#       R   c

# 3:2
# first table  column = second table rows
c = np.transpose(B)


# A*B
c = np.dot(A,c)
print("shape", A.shape)
print("shape",B.shape)
print("C = " , c)
# print(np.dot(A, B))

shape (2, 3)
shape (2, 3)
C =  [[35 38]
 [63 73]]


In [22]:
# logical operations
import numpy as np

a = np.array([10, 20, 30])
b = np.array([20, 20, 10])

print(a == b)   
print(a > b)   
print(a <= 20) 


# Logical operations
print(np.logical_and(a > 10, b < 30))  


[False  True False]
[False False  True]
[ True  True False]
[False  True  True]


In [ ]:
# Broadcasting
import numpy as np

data = np.array([1,2,3,4])

print(data +2)




[3 4 5 6]


In [ ]:
# Aggrigation functions

import numpy as np 

data = np.array([1,2,3,4])





In [ ]:
import numpy as np

a = np.array([[[1,2,3,], [1,2,3], ]])