In [8]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])


print("shape", a.shape)



shape (3, 3)


Three Dimensional arrary

In [74]:
import numpy as np 
b = np.array([[[1,2,3], [4,5,6], [7,8,9] ] , [[1,2,3] ,[4,5,6],[7,8,9]]] )
print("shape", b.shape)
print(b)



shape (2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [27]:
import numpy as np

c = np.zeros((2,3,4))



print("shape", c.shape)

d = np.random.randint(1,100,(2,3,4))


print(d)
print("shape", d.shape)

shape (2, 3, 4)
[[[36 49 59 77]
  [ 5  5 64 77]
  [60 83 60 74]]

 [[ 7  7 75 62]
  [34 49 36 51]
  [90  6 70 22]]]
shape (2, 3, 4)


single dimensional 

In [ ]:
import numpy as np 

e  = np.array([
    [
        np.array([1,2,3]), np.array([4,5,6])  
    ],
    [
        np.array([7,8]) , np.array([10,11,12])
    ]
    ] , dtype=object )

print("shape", e.shape) 

# single dimensional 


    


shape (2, 2)


In [ ]:
import  numpy as np

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] ]

lenght = max(len(row) for block in data  for row in block)

for i in data:
    for j in i:
        l = len(j)

print(l)

5


Tasks

1. syncthtic data
2. 


In [ ]:
# indexing
import  numpy as np

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] ]

print(data)

print(data[0])

print(data[-1])

# task
# on the 0 th  index  take the 1st element 




[[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]]
[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [44]:
# slicing

import numpy as np 

data = [ [[1,2,3,4,5 ,6], [1,2,3,4,5,6]], [[1,2,3,4,5,], [1,2,3,4,5]] , [[1,2,3,4,5,], [1,2,3,4,5]],[[1,2,3,4,5,], [1,2,3,4,5]]]

print(data[0:2])

[[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]]


In [ ]:
# filering
import numpy as np

data =np.array([1,2,3,4,55,6,])

# bool indexing
print(data > 3)

# bool filter by contidion
print(data[data > 3])


[False False False  True  True  True]
[ 4 55  6]


In [ ]:

import numpy  as np

marks = np.array([40,20,34,60,78,90])

print(marks > 40)
print(marks[marks < 40])





[False False False  True  True  True]
[20 34]


In [64]:
# reshaping

import numpy as np



data = np.arange(1,13)

# c = np.zeros((2,3,4))


reshaped  =  data.reshape(2,6)

print(reshaped)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# split
import numpy as np

data = np.arange(1,31)
# does not take the last element 
reshaped = data.reshape(3,10)

print(reshaped)
print("horizontal", np.hsplit(reshaped, 2))
print("verical" ,np.vsplit(reshaped, 3))


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])]
verical [array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]
